backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images/ # Media files will be stored in the repo under static/images/
public_folder: /images/ # The src attribute for uploaded media will begin with /images/uploads

site_url: https://www.ericlugo.dev
logo_url: https://www.ericlugo.dev/images/avatar.svg

publish_mode: editorial_workflow
show_preview_links: false # Can be enabled after getting GraphQL queries and page generation up

collections:
  - name: "projects"
    description: "" # This is an optional description for SEO and Open Graph purposes.
    label: "Projects"
    label_singular: "Project"
    folder: "content/project"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - {
          required: true,
          label: "Title",
          name: "title",
          widget: "string"
        }
      - {
          required: true,
          label: "Description",
          name: "description",
          widget: "text",
        }
      - {
          required: true,
          label: "Publish Date",
          name: "date",
          widget: "datetime",
        }
      - {
          required: false,
          label: "Languages Used",
          name: "languages",
          widget: "list",
        }
      - {
          required: false,
          label: "Libraries Used",
          name: "libraries",
          widget: "list",
        }
      - {
          required: true,
          label: "Body",
          name: "body",
          widget: "markdown"
        }
      - {
          required: false,
          label: "Image(s)",
          name: "image(s)",
          widget: "file",
          media_library: {
            config: {
              multiple: true
            }
          }
        }
  - name: "notes"
    description: "" # This is an optional description for SEO and Open Graph purposes.
    label: "Notes"
    label_singular: "Note"
    folder: "content/note"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - {
          required: true,
          label: "Title",
          name: "title",
          widget: "string"
        }
      - {
          required: true,
          label: "Publish Date",
          name: "date",
          widget: "datetime",
        }
      - {
          required: false,
          label: "Tags",
          name: "tags",
          widget: "list"
        }
      - {
          required: true,
          label: "Body",
          name: "body",
          widget: "markdown"
        }
  - name: "blog"
    description: "" # This is an optional description for SEO and Open Graph purposes.
    label: "Blog"
    folder: "content/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    delete: true
    fields:
      - {
          required: true,
          label: "Title",
          name: "title",
          widget: "string"
        }
      - {
          required: true,
          label: "Description",
          name: "description",
          widget: "text",
        }
      - {
          required: true,
          label: "Publish Date",
          name: "date",
          widget: "datetime",
        }
      - {
          required: true,
          label: "Body",
          name: "body",
          widget: "markdown"
        }
      - {
          required: true,
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Experiment",
              "Technical Writeup",
              "Retrospective",
              "Opinion Piece",
              "Guide",
              "Random Musings of a Madman",
            ],
        }
